version: '3'
services:
  auth-service:
    build: .
    volumes:
      - ./app:/service/app
    ports:
    - "8000:8000"
    networks:
      2read_online:
    command: uvicorn app.main:app --reload --host 0.0.0.0

networks:
  2read_online:
    external: true
